[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
name = "prelude_py"
version = "0.2.0"
description = "Lazy imports for common scientific Python libraries."
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.10"


authors = [
    {name = "David Rodriguez Morales", email = "rodriguezmorales@med.uni-frankfurt.de"}
]
maintainers = [
    {name = "David Rodriguez Morales", orcid = "0000-0002-1819-6991", email = "rodriguezmorales@med.uni-frankfurt.de" }
]

keywords = [
    "scientific-python",
    "lazy-import",
]

classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]


dependencies = [
    "pandas",
    "numpy"
]

[project.urls]
Homepage = "https://github.com/davidrm-bio/prelude_py"
Repository = "https://github.com/davidrm-bio/prelude_py"
Issues = "https://github.com/davidrm-bio/prelude_py/issues"



[project.optional-dependencies]
all = [
    "numpy",
    "numba",
    "pandas",
    "polars",
    "matplotlib",
    "seaborn",
    "anndata",
    "scanpy",
    "dotools_py",
    "decoupler",
    "squidpy",
    "scvi-tools",
    "pertpy",
]

dev = [
    "pre-commit",
]

test = [
    "pytest>=8",
    "coverage[toml]",

    "numpy",
    "numba",
    "pandas",
    "polars",
    "matplotlib",
    "seaborn",
    "anndata",
    "scanpy",
    "dotools_py",
    "decoupler",
    "squidpy",
    "scvi-tools",
    "pertpy",
]



[tool.hatch.envs.default]
installer = "uv"
features = ["dev"]

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.11", "3.13"]
deps = ["stable"]

[tool.hatch.envs.hatch-test]
features = ["test"]



[tool.pytest.ini_options]
testpaths = ["tests"]
xfail_strict = true
addopts = [
    "--import-mode=importlib",
]


[tool.coverage.run]
source = ["prelude_py"]
